 var stop;
 var stopsub; 
 var curmenu;
 var submenu;
 var thousands_start=100;
 var menuwidth=200; 
 var menuheight=50;
 var menu = new Menu();
menu.addItem('handbags','?p=search&CLASSS=handbags');
menu.addsubmenu();
menu.addsubmenuitem('39','?p=search&T_CHILD=39&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=39&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('99','?p=search&T_CHILD=99&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=99&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Anya hindmarch','?p=search&T_CHILD=Anya hindmarch&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Anya hindmarch&T_CLASS=handbags&sex=2');
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Anya hindmarch&T_CLASS=handbags&sex=0');
menu.addsubmenuitem('Balenciaga','?p=search&T_CHILD=Balenciaga&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Balenciaga&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Chanel','?p=search&T_CHILD=Chanel&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Chanel&T_CLASS=handbags&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Chanel&T_CLASS=handbags&sex=1');
menu.addsubmenuitem('Chloe','?p=search&T_CHILD=Chloe&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Chloe&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Christian dior','?p=search&T_CHILD=Christian dior&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Christian dior&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Fendi','?p=search&T_CHILD=Fendi&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Fendi&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Hermes','?p=search&T_CHILD=Hermes&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Hermes&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Jimmy choo','?p=search&T_CHILD=Jimmy choo&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Jimmy choo&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Lacoste','?p=search&T_CHILD=Lacoste&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Lacoste&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Louis vuitton','?p=search&T_CHILD=Louis vuitton&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Louis vuitton&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Miu miu','?p=search&T_CHILD=Miu miu&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Miu miu&T_CLASS=handbags&sex=2');
menu.addsubmenuitem('Prada','?p=search&T_CHILD=Prada&T_CLASS=handbags');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Prada&T_CLASS=handbags&sex=2');

menu.addItem('Sunglasses','?p=search&CLASSS=Sunglasses');
menu.addsubmenu();
menu.addsubmenuitem('37','?p=search&T_CHILD=37&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=37&T_CLASS=Sunglasses&sex=2');
menu.addsubmenuitem('Chanel','?p=search&T_CHILD=Chanel&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Chanel&T_CLASS=Sunglasses&sex=2');
menu.addsubmenuitem('Christian dior','?p=search&T_CHILD=Christian dior&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Christian dior&T_CLASS=Sunglasses&sex=0');
menu.addsubmenuitem('DG','?p=search&T_CHILD=DG&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=DG&T_CLASS=Sunglasses&sex=0');
menu.addsubmenuitem('Emporio Armani','?p=search&T_CHILD=Emporio Armani&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Emporio Armani&T_CLASS=Sunglasses&sex=0');
menu.addsubmenuitem('Fendi','?p=search&T_CHILD=Fendi&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Fendi&T_CLASS=Sunglasses&sex=0');
menu.addsubmenuitem('Ferragamo','?p=search&T_CHILD=Ferragamo&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Ferragamo&T_CLASS=Sunglasses&sex=0');
menu.addsubmenuitem('Gucci','?p=search&T_CHILD=Gucci&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Gucci&T_CLASS=Sunglasses&sex=0');
menu.addsubmenuitem('Oakley','?p=search&T_CHILD=Oakley&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Oakley&T_CLASS=Sunglasses&sex=0');
menu.addsubmenuitem('Police','?p=search&T_CHILD=Police&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Police&T_CLASS=Sunglasses&sex=0');
menu.addsubmenuitem('Ray Ban','?p=search&T_CHILD=Ray Ban&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Ray Ban&T_CLASS=Sunglasses&sex=0');
menu.addsubmenuitem('Versace','?p=search&T_CHILD=Versace&T_CLASS=Sunglasses');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Versace&T_CLASS=Sunglasses&sex=0');

menu.addItem('Jeans','?p=search&CLASSS=Jeans');
menu.addsubmenu();
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Jeans');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Jeans&sex=1');
menu.addsubmenuitem('Affliction','?p=search&T_CHILD=Affliction&T_CLASS=Jeans');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Affliction&T_CLASS=Jeans&sex=1');
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=Jeans');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=Jeans&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ed hardy&T_CLASS=Jeans&sex=1');
menu.addsubmenuitem('Rock republic','?p=search&T_CHILD=Rock republic&T_CLASS=Jeans');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Rock republic&T_CLASS=Jeans&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Rock republic&T_CLASS=Jeans&sex=1');
menu.addsubmenuitem('Seven','?p=search&T_CHILD=Seven&T_CLASS=Jeans');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Seven&T_CLASS=Jeans&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Seven&T_CLASS=Jeans&sex=1');
menu.addsubmenuitem('True religion','?p=search&T_CHILD=True religion&T_CLASS=Jeans');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=True religion&T_CLASS=Jeans&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=True religion&T_CLASS=Jeans&sex=1');

menu.addItem('Bikini','?p=search&CLASSS=Bikini');
menu.addsubmenu();
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Billabong','?p=search&T_CHILD=Billabong&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Billabong&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Burberry','?p=search&T_CHILD=Burberry&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Burberry&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Chanel','?p=search&T_CHILD=Chanel&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Chanel&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Chloe','?p=search&T_CHILD=Chloe&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Chloe&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Christian dior','?p=search&T_CHILD=Christian dior&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Christian dior&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Coach','?p=search&T_CHILD=Coach&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Coach&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('DG','?p=search&T_CHILD=DG&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=DG&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Gucci','?p=search&T_CHILD=Gucci&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Gucci&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Louis vuitton','?p=search&T_CHILD=Louis vuitton&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Louis vuitton&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Miu miu','?p=search&T_CHILD=Miu miu&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Miu miu&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Other','?p=search&T_CHILD=Other&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Other&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Parah','?p=search&T_CHILD=Parah&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Parah&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Prada','?p=search&T_CHILD=Prada&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Prada&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Ralph lauren','?p=search&T_CHILD=Ralph lauren&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ralph lauren&T_CLASS=Bikini&sex=2');
menu.addsubmenuitem('Roxy','?p=search&T_CHILD=Roxy&T_CLASS=Bikini');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Roxy&T_CLASS=Bikini&sex=2');

menu.addItem('Flip flop','?p=search&CLASSS=Flip flop');
menu.addsubmenu();
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Flip flop');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Flip flop&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Flip flop&sex=1');
menu.addsubmenuitem('Billabong','?p=search&T_CHILD=Billabong&T_CLASS=Flip flop');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Billabong&T_CLASS=Flip flop&sex=2');
menu.addsubmenuitem('COACH','?p=search&T_CHILD=COACH&T_CLASS=Flip flop');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=COACH&T_CLASS=Flip flop&sex=2');
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=Flip flop');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=Flip flop&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ed hardy&T_CLASS=Flip flop&sex=1');
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Flip flop');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Flip flop&sex=2');

menu.addItem('Tracksuit','?p=search&CLASSS=Tracksuit');
menu.addsubmenu();
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=Tracksuit');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=Tracksuit&sex=2');
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Tracksuit');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Tracksuit&sex=2');

menu.addItem('Kids','?p=search&CLASSS=Kids');
menu.addsubmenu();
menu.addsubmenuitem('19.5','?p=search&T_CHILD=19.5&T_CLASS=Kids');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=19.5&T_CLASS=Kids&sex=2');
menu.addsubmenuitem('28','?p=search&T_CHILD=28&T_CLASS=Kids');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=28&T_CLASS=Kids&sex=2');
menu.addsubmenuitem('33','?p=search&T_CHILD=33&T_CLASS=Kids');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=33&T_CLASS=Kids&sex=2');
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=Kids');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=Kids&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ed hardy&T_CLASS=Kids&sex=1');
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Kids');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Kids&sex=2');

menu.addItem('Jewelry','?p=search&CLASSS=Jewelry');
menu.addsubmenu();
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Jewelry');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Jewelry&sex=2');

menu.addItem('Tee','?p=search&CLASSS=Tee');
menu.addsubmenu();
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Tee');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Tee&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Tee&sex=1');
menu.addsubmenuitem('AFFLICTION ','?p=search&T_CHILD=AFFLICTION &T_CLASS=Tee');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=AFFLICTION &T_CLASS=Tee&sex=1');
menu.addsubmenuitem('Burberry','?p=search&T_CHILD=Burberry&T_CLASS=Tee');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Burberry&T_CLASS=Tee&sex=1');
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=Tee');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=Tee&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ed hardy&T_CLASS=Tee&sex=1');
menu.addsubmenuitem('Fred perry','?p=search&T_CHILD=Fred perry&T_CLASS=Tee');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Fred perry&T_CLASS=Tee&sex=1');
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Tee');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Tee&sex=2');
menu.addsubmenuitem('Lacoste','?p=search&T_CHILD=Lacoste&T_CLASS=Tee');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Lacoste&T_CLASS=Tee&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Lacoste&T_CLASS=Tee&sex=1');
menu.addsubmenuitem('Ralph laure(national flag)','?p=search&T_CHILD=Ralph laure(national flag)&T_CLASS=Tee');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ralph laure(national flag)&T_CLASS=Tee&sex=1');
menu.addsubmenuitem('Ralph lauren','?p=search&T_CHILD=Ralph lauren&T_CLASS=Tee');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ralph lauren&T_CLASS=Tee&sex=1');

menu.addItem('Jacket','?p=search&CLASSS=Jacket');
menu.addsubmenu();
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Jacket');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Jacket&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Jacket&sex=1');
menu.addsubmenuitem('Canada goose','?p=search&T_CHILD=Canada goose&T_CLASS=Jacket');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Canada goose&T_CLASS=Jacket&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Canada goose&T_CLASS=Jacket&sex=1');
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=Jacket');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=Jacket&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ed hardy&T_CLASS=Jacket&sex=1');
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Jacket');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Jacket&sex=2');
menu.addsubmenuitem('Peak','?p=search&T_CHILD=Peak&T_CLASS=Jacket');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Peak&T_CLASS=Jacket&sex=1');

menu.addItem('Dress','?p=search&CLASSS=Dress');
menu.addsubmenu();
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Dress');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Dress&sex=2');

menu.addItem('Caps','?p=search&CLASSS=Caps');
menu.addsubmenu();
menu.addsubmenuitem('13.5','?p=search&T_CHILD=13.5&T_CLASS=Caps');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=13.5&T_CLASS=Caps&sex=2');
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Caps');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Caps&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Caps&sex=1');
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=Caps');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ed hardy&T_CLASS=Caps&sex=1');
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Caps');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Caps&sex=2');

menu.addItem('Wallets','?p=search&CLASSS=Wallets');
menu.addsubmenu();
menu.addsubmenuitem('Chanel','?p=search&T_CHILD=Chanel&T_CLASS=Wallets');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Chanel&T_CLASS=Wallets&sex=2');
menu.addsubmenuitem('Gucci','?p=search&T_CHILD=Gucci&T_CLASS=Wallets');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Gucci&T_CLASS=Wallets&sex=0');
menu.addsubmenuitem('Louis vuitton','?p=search&T_CHILD=Louis vuitton&T_CLASS=Wallets');
menu.addlevel2menu();
menu.addlevel2menuitem('Unsex style','?p=search&T_CHILD=Louis vuitton&T_CLASS=Wallets&sex=0');

menu.addItem('sleepwear','?p=search&CLASSS=sleepwear');
menu.addsubmenu();
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=sleepwear');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ed hardy&T_CLASS=sleepwear&sex=1');

menu.addItem('Shoes','?p=search&CLASSS=Shoes');
menu.addsubmenu();
menu.addsubmenuitem('Juicy couture','?p=search&T_CHILD=Juicy couture&T_CLASS=Shoes');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Juicy couture&T_CLASS=Shoes&sex=2');

menu.addItem('Boot','?p=search&CLASSS=Boot');
menu.addsubmenu();
menu.addsubmenuitem('UGG','?p=search&T_CHILD=UGG&T_CLASS=Boot');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=UGG&T_CLASS=Boot&sex=2');

menu.addItem('Dress shirt','?p=search&CLASSS=Dress shirt');
menu.addsubmenu();
menu.addsubmenuitem('Emporio Armani','?p=search&T_CHILD=Emporio Armani&T_CLASS=Dress shirt');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Emporio Armani&T_CLASS=Dress shirt&sex=1');
menu.addsubmenuitem('Paul smith','?p=search&T_CHILD=Paul smith&T_CLASS=Dress shirt');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Paul smith&T_CLASS=Dress shirt&sex=1');
menu.addsubmenuitem('Ralph lauren','?p=search&T_CHILD=Ralph lauren&T_CLASS=Dress shirt');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ralph lauren&T_CLASS=Dress shirt&sex=1');
menu.addsubmenuitem('Versace','?p=search&T_CHILD=Versace&T_CLASS=Dress shirt');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Versace&T_CLASS=Dress shirt&sex=1');

menu.addItem('工笔','?p=search&CLASSS=工笔');
menu.addsubmenu();
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=工笔');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=工笔&sex=1');

menu.addItem('underwear','?p=search&CLASSS=underwear');
menu.addsubmenu();
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=underwear');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=underwear&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ed hardy&T_CLASS=underwear&sex=1');

menu.addItem('Hoody','?p=search&CLASSS=Hoody');
menu.addsubmenu();
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Hoody');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Hoody&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Hoody&sex=1');

menu.addItem('Shorts','?p=search&CLASSS=Shorts');
menu.addsubmenu();
menu.addsubmenuitem('37','?p=search&T_CHILD=37&T_CLASS=Shorts');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=37&T_CLASS=Shorts&sex=1');
menu.addsubmenuitem('37.5','?p=search&T_CHILD=37.5&T_CLASS=Shorts');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=37.5&T_CLASS=Shorts&sex=1');
menu.addsubmenuitem('Abercrombie Fitch','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Shorts');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Shorts&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Abercrombie Fitch&T_CLASS=Shorts&sex=1');
menu.addsubmenuitem('BAPE','?p=search&T_CHILD=BAPE&T_CLASS=Shorts');
menu.addlevel2menu();
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=BAPE&T_CLASS=Shorts&sex=1');
menu.addsubmenuitem('Ed hardy','?p=search&T_CHILD=Ed hardy&T_CLASS=Shorts');
menu.addlevel2menu();
menu.addlevel2menuitem('Women style','?p=search&T_CHILD=Ed hardy&T_CLASS=Shorts&sex=2');
menu.addlevel2menuitem('Men style','?p=search&T_CHILD=Ed hardy&T_CLASS=Shorts&sex=1');

menu.showMenu();